### PR TITLE
Add support for custom action

### LINKED ISSUE #104: Custom actions?
Is it possible for us to pass a link to MailGo as an option and have it rendered as a custom action? 

For example, in the [CiviCRM integration](https://civicrm.org/extensions/commlink) it would be beneficial if we could replicate a core function when we override email links. That core function lets us create a CRM "activity" when clicking on an email. If we could add an "Open activity" action - we'd replicate the current status quo and add the amazing additional options provided by MailGo :-)

### PR DESCRIPTION
**Pull request by gianantoniopini**
Fixes #104 :
- added new "custom" action
- added support for new `data-custom-action-text` and `data-custom-action-url` attributes, which can be specified in the mailto: links
- added unit tests for this new "custom action" functionality
- this new "custom" action will only work when mailgo is used with mailto: links. So it is not supported, at least for now, with tel: or callto: links and with mailgo direct render

Other:
- Also added some basic unit tests for already existing functionality (usage with mailto and tel)

### CODE REVIEW

**Comment by manzinello** [comment]
Thank you!

**Comment by gianantoniopini** [comment]
Pleasure, thanks!

**Comment by homotechsual** [comment]
Thanks for this :-) @manzinello do you think there's enough since the last release to put out a newer release?

**Comment by manzinello** [comment]
> do you think there's enough since the last release to put out a newer release?

Absolutely yes. I will release a new version asap, surely in this week. Thank you so much for your work.

**Comment by manzinello** [comment]
Released **mailgo 0.12.0**!

**Comment by homotechsual** [comment]
I don't see the release on GitHub yet but thanks for this!

**Comment by manzinello** [comment]
Added now on GitHub releases, I have released it on NPM (https://www.npmjs.com/package/mailgo) before!

**Pull request merged**
